# primary environment 

name: gsnn

channels: 
    - pytorch 
    - nvidia 
    - pyg
    - conda-forge
    - mcs07
    - defaults 

dependencies:
    - python
    - matplotlib
    - pyg
    - pytorch
    - seaborn
    - scikit-learn
    - h5py
    - scipy
    - tensorboard
    - statsmodels
    - pip
    - pyro-ppl
    - pip:
        - tensorboardX
        - ipykernel
        - umap-learn
        - torch-sparse 
        - torch-scatter
        - torch-cluster
        - pytest
        - ax-platform
