name: gsnn

channels: 
    - defaults 
    - pytorch 
    - nvidia 
    - conda-forge
    - pyg
    - mcs07

dependencies:
    - python=3.10
    - matplotlib
    - pubchempy
    - pyg
    - pytorch::pytorch=2.0
    - pytorch::torchvision
    - pytorch::torchaudio
    - pytorch-cuda=11.7
    - seaborn
    - scikit-learn
    - h5py
    - scipy
    - tensorboard
    - shapely
    - statsmodels
    - pip
    - rdkit
    - shap
    - pytorch-scatter
    - pip:
        - tensorboardX
        - ipykernel
        - umap-learn
        - biopython
        - obonet
        - omnipath 
        - adjustText
