name: gsnn

channels: 
    - pytorch 
    - pyg
    - conda-forge
    - defaults 

dependencies:
    - python
    - matplotlib
    - pyg::pyg
    - pytorch::pytorch
    - seaborn
    - scikit-learn
    - h5py
    - scipy
    - tensorboard
    - statsmodels
    - pip
    - pyro-ppl
    - pip:
        - tensorboardX
        - ipykernel
        - umap-learn
        - pytest
        - ax-platform
